### PR TITLE
Added compatibility for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by stephenogg**
To enable compatibility with Ubuntu 20.04, the omero_server_python_requirements_ice_package variable needs to point to the correct version of ice depending on the distro.

I also had to remove the reference to "omero_server_systemd_require_network", so that the systemd file is created without it, otherwise I get an error about  "unit network.service not found" when omero-server tries to start. I guess this will be related to PR #53.

### CODE REVIEW

**Comment by joshmoore** [comment]
Same comments as https://github.com/ome/ansible-role-omero-web/pull/38#issuecomment-754619633

I'll leave @manics to comment on the change related to https://github.com/ome/ansible-role-omero-server/pull/53

**Review by manics — COMMENTED** [review]
Looks fine to me. I haven't tested it though- is someone willing to add a molecule test scenario for the two new platforms? Either in this PR or a follow-up. Probably best to:
- copy https://github.com/ome/ansible-role-omero-server/tree/3.3.0/molecule/python3-ubuntu1804
- rename https://github.com/ome/ansible-role-omero-server/tree/3.3.0/molecule/python3 to `python3-centos7`

**Comment by SteveO-sudo** [comment]
Uhhhhh? Molecule test scenarios? What's that?

I tried using @manics advice about copying/renaming. But someone who knows had better check. All I did was to change the image to some seemingly correct image from docker hub and change the name of the test. And added the omero_server_selfsigned_certificates: true for the centos8 test because it's using the newest openssl.

**Comment by sbesson** [comment]
I have merged `origin/master` into this branch, fixed the conflicts arising from the [PR dropping Python 2 support](#56) and the yamllint errors.

The CentOS 8 Molecule scenario failed with an error in an upstream role - see https://github.com/sbesson/ansible-role-omero-server/runs/2201526384?check_suite_focus=true so I removed the scenario.

I would propose to stick to the original intent of this PR i.e. add native support for Ubuntu 20.04, get this merged and released as `4.0.0` and start consuming it in our (example playbooks](https://github.com/ome/omero-deployment-examples).
@SteveO-sudo @joshmoore any objections with this proposal?

**Comment by SteveO-sudo** [comment]
None from me. Thank you!

**Comment by joshmoore** [comment]
No objections.

**Pull request merged**
