### PR TITLE
Do not pin OMERO.server version to 5.6.0-rc1 in Molecule

### PR DESCRIPTION
**Pull request by sbesson**
Try removing the hardcoded pinning to a release candidate version of the server in one of the Molecule tests

### CODE REVIEW

**Comment by sbesson** [comment]
From https://travis-ci.org/github/ome/ansible-role-omero-server/jobs/666726680, the `upgrade-py2py3` scenario is failing with an `Ice::UnmarshalOutOfBoundsException`. Need to investigate more unless someone has an intuition of what is going wrong.

**Comment by joshmoore** [comment]
thanks, @mtbc. @sbesson : you want this as an immediate release? If so, `3.2.1 v 3.3.0`?

**Comment by sbesson** [comment]
As this PR is modifying a Molecule file used for CI testing, I am not sure a release would bring much value to consumers of the role. Otherwise, I would go for a patch release i.e. `3.2.1`.

**Comment by joshmoore** [comment]
> I am not sure a release would bring much value to consumers of the role

:+1:

**Pull request merged**
